### ISSUE TITLE
NetBeans frets and isn't quite there

### ISSUE THREAD

**Issue by rvowles** [repaint-io/maven-tiles#10]
NetBeans recognizes there is a custom build component and frets, but as long as dependencies are not in your tiles, it just doesn't discover the plugins and present them to you. It does build with tiles fine, so development is not affected.

**Comment by rvowles** [comment]
closing as no one cares about netbeans anymore

**Comment by CarstenWickner** [comment]
Kia ora Richard,

Were there any leads on how to solve the "external build participants" problem for Netbeans before your judgement here? 😅
I'm looking for help elsewhere too (https://stackoverflow.com/q/69206222/5127499), but no luck so far.
My issue is particularly with the `maven-compiler-plugin`. Without its presence in the `pom.xml`, Netbeans refuses to compile with the right JDK during its automatic project loading.

**Comment by dermot-hardy** [comment]
See https://github.com/apache/netbeans/pull/4630.

You can disable the warning easily enough by creating setting the `ignoreOnModelLoad` flag:

![image](https://github.com/repaint-io/maven-tiles/assets/20627297/415bce20-ab49-4bd5-82ea-7cf68f4b796d)
