### ISSUE TITLE
Illegal folder created for maven-compiler-plugin support on Windows

### ISSUE THREAD

**Issue by injecto** [repaint-io/maven-tiles#105]
> Apache Maven 3.6.1 (d66c9c0b3152b2e69ee9bac180bb8fcc8e6af555; 2019-04-04T22:00:29+03:00)
> Maven home: C:\Program Files\maven\apache-maven-3.6.1
> Java version: 1.8.0_212, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk1.8.0_212\jre
> Default locale: ru_MD, platform encoding: Cp1251
> OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

Compilation error:

> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (com.unitedtraders.luna.maventiles2:base-java-tile:2.1.0::java-compile) on project mobile-gateway-api: Error while storing the mojo status: C:\work\mobile-gateway-proto-api\mobile-gateway-api\target\maven-status\maven-compiler-plugin\compile\com.unitedtraders.luna.maventiles2:base-java-tile:2.1.0::java-compile\createdFiles.lst (Синтаксическая ошибка в имени файла, имени папки или метке тома)

Colons are illegal characters in windows paths, but tiles plugin overwrite original execution ID.

The obvious workaround is to use `tiles-keep-id` configuration, but overwritten ID must be cross-platform maybe?

**Comment by talios** [comment]
@injecto This should be fixed now in the new released, have switched out to using `_` as a separator rather than the traditional `:` for a GAV specifier.
