### ISSUE TITLE
revision property of parent is not resolved if using plugin in combination with flatten-plugin

### ISSUE THREAD

**Issue by repolevedavaj** [repaint-io/maven-tiles#109]
I have an issue using this plugin in combination with the revision property and flatten-maven-plugin in a multi-module project setup. I am using the flatten-plugin with mode `clean` but without updating poms of modules with packaging `pom`. Also I use the revision property to set my project version. Therefore the installed pom file of a module with packaging 'pom' will the same as the original (with `${revision}` as version). Now if configure the maven-tiles plugin in a leaf project and start Maven, I run into the following error:

```
[ERROR] Error executing Maven.
[ERROR] Missing:
----------
1) x.y.z:root:pom:${revision}
----------
1 required artifact is missing.
```

If I run the build without the tiles-plugin, the build succeeds normally.

I created a minimal example project for my issue: https://github.com/repolevedavaj/tiles-maven-plugin-with-flatten-test

**Comment by rvowles** [comment]
we don't support multi-module pom files, only reactor pom files (reactor indicates which ones to build and that is all). have  you tried moving your plugin to a tile?

**Comment by repolevedavaj** [comment]
Yes, it seems that the problem only exists with multi-module projects. It is a pity that we cannot use this plugin in our current setup. Thanks for your feedback!
