### ISSUE TITLE
Plugin Execution Order

### ISSUE THREAD

**Issue by bmlong137** [repaint-io/maven-tiles#118]
The order of executions of the same plugin group/artifact appears to be happening based on some underlying characteristic instead of anything that can be configured.  For instance:

### tile1.xml (T1)
```xml
<project>
  <build>
    <plugins>
      <plugin>
        <groupId>G1</groupId>
        <artifactId>A1</artifactId>
        <version>V1</version>
        <executions>
          <execution>
             <id>E1</id>
             <phase>P1</phase>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
```

### tile2.xml (T2)
```xml
<project>
  <build>
    <plugins>
      <plugin>
        <groupId>G1</groupId>
        <artifactId>A1</artifactId>
        <version>V1</version>
        <executions>
          <execution>
             <id>E2</id>
             <phase>P1</phase>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
```

### pom.xml
```xml
<project>
  ...
  <tiles>
    <tile>group:T1:version</tile>
    <tile>group:T2:version</tile>
  </tiles>
  ...
</project>
```

No matter what I do with the tile order in the POM, or how I name the executions (IDs) alphabetically, the execution order does not change between E1 and E2.

I took a look at the source to see if an unordered data set could be at fault, causing a hash code to be the predictor, but I couldn't find it.  However, it appears that it could still be something like a hash code dictating it.  Maven itself guarantees the execution order to be in the order that execution elements show up in the POM...parent first.  So I would have thought tile order would matter...

If I am write that this is unexpected behavior, I could create a test case.  I might just hack away at it myself.  It is causing me headaches.

**Comment by bmlong137** [comment]
I have found that if I use different plugin artifacts on the same phase across multiple tiles, the execution order is the reverse of the declared tile order.  I am currently assuming this is the case with the same plugin artifact, but with multiple executions across multiple tiles.

The problem seems to be when there is an execution declared inside a tile that is inside a tile.  Those tile-in-tile declarations are going first no matter what.  And that could be the heart of the issue.

**Comment by talios** [comment]
Hey @bmlong137 - thanks for the ticket.  Mmmm, I'm in times (and have been for awhile) about those tiles-with-tiles being largely smells and if we should even support that.

If you can add a PR/branch somewhere with an invoker test that would be awesome and help out a lot.

**Comment by bmlong137** [comment]
Created IT case with pull request #119.  Have at it. :+1:

**Comment by bmlong137** [comment]
In an attempt to flush this out, I did some research in the code.  I am a Java developer; not groovy.  And this is my first look into the code behind Maven Tiles.

The merging of execution blocks seems sequential.  This is as one would expect, as the Maven spec calls for the execution of same-phase executions in the order in which the appear in the POM; parent first.  The problem is centered on the processing order of the tiles, not the execution blocks.

I suspect the iteration of tiles is happening in the [`loadAllDiscoveredTiles` method](https://github.com/repaint-io/maven-tiles/blob/4a16a4360d8f4e2cad480dfdb55a3970a066d8db/src/main/groovy/io/repaint/maven/tiles/TilesMavenLifecycleParticipant.groovy#L694).  I also suspect that the call to the [`loadModel` method](https://github.com/repaint-io/maven-tiles/blob/4a16a4360d8f4e2cad480dfdb55a3970a066d8db/src/main/groovy/io/repaint/maven/tiles/TilesMavenLifecycleParticipant.groovy#L702) is handing off control of processing tiles within tiles to the Maven model processor, which eventually calls back into this extension, but makes it more difficult to reorg.  This would mean the merges are happening with the deepest tiles within tiles first and tiles within POMs are always last.

**Comment by bmlong137** [comment]
I am guessing the ultimate solution would be hold off on the `mergeTileIntoTarget` method until some point after the `afterProjectsRead` method.  That is if the `afterProjectsRead` is being executed for each tile project read.

**Comment by bmlong137** [comment]
Ok, I see now.

The [`processConfigurationTile` method](https://github.com/repaint-io/maven-tiles/blob/4a16a4360d8f4e2cad480dfdb55a3970a066d8db/src/main/groovy/io/repaint/maven/tiles/TilesMavenLifecycleParticipant.groovy#L846) adds all the immediate tiles to the `unprocessedTiles` map.  The `loadAllDiscoveredtiles` method is invoked afterwards, which then adds all the tiles-in-tiles to the `unprocessedTiles` map....while moving tiles form "unprocessed" to "processed".  In the example above, this results in the following: TA, TB, TC, TM, TZ, and TN.  The tiles-in-tiles are exactly as I would expect.  It is the root tiles that are not.

**Comment by bmlong137** [comment]
One of two ways to resolve this.
1. We could inject the processing of tiles-in-tiles to the front of the `unprocessedTiles` map.  This would be difficult as it would screw up the tiles-in-tiles order, which is currently correct.
2. We could copy/clear the `unprocessedTiles` map at the beginning of `loadAllDiscoveredTiles`.  Then process those in a loop.  The current loop would be inside that loop.  This would ensure the tiles-in-tiles are added to the `processedTiles` before the next root tile is added to it.

I am going to go ahead an make the change as (2) and throw up a pull request.

**Comment by talios** [comment]
Thanks for the PR.

**Comment by bmlong137** [comment]
thanks for including it. 👍
