### ISSUE TITLE
Tile execution id rewritting should be disableable

### ISSUE THREAD

**Issue by talios** [repaint-io/maven-tiles#12]
In one variant of our tiles we define a execution solely for the purposes of _disabling_ the current behavior. However - now that the `maven-tiles-plugin` prepends the tile GAV to the execution id, this no longer over-writes the default execution.

So we need a way to disable that, on a case-by-case basis - as part of the tile definition.

**Comment by rvowles** [comment]
What on earth are you talking about?

**Comment by talios** [comment]
You'll note when you run a maven build, the execution ID is rewritten to include the source tile GAV:

    [INFO] --- versions-maven-plugin:2.2:display-plugin-updates (com.theoryinpractise:halbuilder-release-tile:1.0.5-SNAPSHOT::version-checks) @ halbuilder-styleguide-tile ---

However, there was a need at one point that we wanted to NOT have that happen. Seems we did work around it, so we could close this.

Maybe just reword the ticket to _document_ the execution id rewriting.

**Comment by erwint** [comment]
We run into the same problem, so I have proposed a fix. If the execution in the tile has a special attribute on the configuration, the id is left untouched.
