### ISSUE TITLE
Packaging causing some pain

### ISSUE THREAD

**Issue by rvowles** [repaint-io/maven-tiles#13]
You cannot specify a packaging Maven doesn't inherently understand  because it attempts to resolve everything first time through. 

This is a reminder to see if we can override the packaging when we attempt to resolve the model the second time. Such as with a \<configuration>\<packaging> setting

**Comment by talios** [comment]
I think this can be closed yes @rvowles ?

**Comment by rvowles** [comment]
it was around your pain for osgi, but nothing will help that, so closing is good.
