### ISSUE TITLE
Could not find tiles when using snapshot from a repository manager

### ISSUE THREAD

**Issue by xfr-dev** [repaint-io/maven-tiles#14]
With snapshot version of a tile, it works fine locally when using maven install command.
But, when deployed to a repository manager (ie Artifactory), Maven never find the tile and seems to not look into the specified snapshot repository. Only the release repository is used instead.
Fyi, It works fine with not snapshot version locally and remotely.

**Comment by kriegaex** [comment]
This issue is not so new anymore and IMO it makes tiles unusable. I cannot even build the sample project. I expect tiles to be read from my local repository even if not deployed to a repo manager at all.

**Comment by talios** [comment]
I really wish I knew HOW to fix it as well.

Not sure whats up with the sample project - I don't think that ever worked actually.  I should update it - currently theres a stash of reviews open in gerrithub ( https://review.gerrithub.io/#/q/project:repaint-io/maven-tiles+status:open ) that need reviewing/merging/releasing - the current 2.0.1 release is fundamentally broken and these fixes have sadly become languished with $work getting in the way ).

I'm tempted to just merge them and get a release out and kick the tires on tiles again...

**Comment by talios** [comment]
...and just merged.

**Comment by talios** [comment]
I just got hit with this again, what what investigation I did this morning, a) we're not copying the `<repositories>` element of a model (raised as #35 ), but also it looks like when using maven mirrors the `<snapshots><enabled>true</enabled></snapshots>` setting is dropped, so even tho the repository may contain SNAPSHOTS which get picked up in version range metadata, the SNAPSHOT is never resolved as maven is told to NOT resolve it.

I might do some more investigation and possibly post on the maven list about this, but either range resolution shouldn't be returning SNAPSHOT ranges for a repo thats not enabled for SNAPSHOTs, or the snapshot=true state should be carried forward. Either way, it looks like it may be a maven issue.

One work around I've seen suggested, but havn't had a chance to try yet is to change ones mirror settings to exclude your snapshot repo using `<mirrorOf>!mySnapshotRepoId, *</mirrorOf>`.

Review for #35 at https://review.gerrithub.io/249566 Copy respositories of a model along with the pluginRepositories )

**Comment by rvowles** [comment]
repositories were left out deliberately so that people couldn't bring repositories in via tiles. We found that with pluginRepositories then stuff wouldn't work, so I wonder if we are hitting the same issue with repositories?

**Comment by talios** [comment]
Rather than silently dropping the `<repositories>` maybe it should be a fast-fail/warning/smell on the production of the tile ( I'd probably lean toward smell/warning ).

However, I'm not sure - maven by default _does not_ resolve SNAPSHOT artifacts from a repository unless you _declare_ the repository and enable SNAPSHOTs.

Good news tho - I have managed to resolve the issue, or... side step it with actual maven config. In my `~/.m2/settings.xml` to contain:

    <mirrors>
      <mirror>
        <id>Nexus</id>
        <name>Nexus Public Mirror</name>
        <url>http://mynexus/nexus/content/groups/public</url>
        <mirrorOf>!smx3-snapshots,*</mirrorOf>
      </mirror>
    </mirrors>
    ....
    <profile>
      <id>smx</id>
      <repositories>
          <repository>
            <id>smx3-snapshots</id>
            <url>http://mynexus/nexus/content/repositories/snapshots/</url>
            <snapshots>
              <enabled>true</enabled>
            </snapshots>
            <releases>
              <enabled>false</enabled>
            </releases>
          </repository>
        </repositories>
      </profile>
    </profiles>
    <activeProfiles>
      <activeProfile>smx</activeProfile>
    </activeProfiles>

This tells maven to enable a profile that defines a `SNAPSHOT` enabled repository, which is also NOT mirrored ( `!smx3-snapshots` in the `<mirrorOf>` element ) so that maven goes to it directly. Adding in some debug on the tiles plugin I see:


           id: Nexus
          url: http://mynexus/nexus/content/groups/public
       layout: default
    snapshots: [enabled => false, update => daily]
     releases: [enabled => true, update => daily]

           id: smx3-snapshots
          url: http://mynexus/nexus/content/repositories/snapshots/
       layout: default
    snapshots: [enabled => true, update => daily]
     releases: [enabled => false, update => daily]
     
and in the standard maven output I see:

     [INFO] --- tiles-maven-plugin: Injecting 4 tiles as intermediary parent artifact's...
     [INFO] Mixed 'com.smxemail:com.smxemail.datatype:1.4.7-SNAPSHOT' with tile 'com.smxemail.tiles:com.smxemail.tiles.release:2.0.2' as it's new parent.
     [INFO] Mixed 'com.smxemail.tiles:com.smxemail.tiles.release:2.0.2' with tile 'com.smxemail.tiles:com.smxemail.tiles.enforcements:2.0.3-20151013.021527-1' as it's new parent.
     [INFO] Mixed 'com.smxemail.tiles:com.smxemail.tiles.enforcements:2.0.3-20151013.021527-1' with tile 'com.smxemail.tiles:com.smxemail.tiles.osgiapi:2.0.1' as it's new parent.
     [INFO] Mixed 'com.smxemail.tiles:com.smxemail.tiles.osgiapi:2.0.1' with tile 'com.smxemail.tiles:com.smxemail.tiles.karaffeature:2.0.1' as it's new parent.
     [INFO] Mixed 'com.smxemail.tiles:com.smxemail.tiles.karaffeature:2.0.1' with original parent 'com.smxemail:com.smxemail.parent:2.1.16' as it's  new top level parent.

Which you can see the timestamped SNAPSHOT being mixed in.

Maybe we simple add this information into the `README.adoc` or a new `FAQ.adoc` and close the issue?

**Comment by talios** [comment]
Note - I was seeing this fail when using `<activeByDefault>` inside the profile defintion, but including the profile in the `<activeProfiles>` element seemed to work.

**Comment by rvowles** [comment]
You will need to talk me through this @talios - is there a TL;DR summary somewhere?
