### ISSUE TITLE
Plugin validation issues due to dependencies on deprecated Maven 2.x compatibility layer

### ISSUE THREAD

**Issue by lfvjimisola** [repaint-io/maven-tiles#143]
Using Maven 3.9.5 with tiles-maven-plugin:2.36 will output the following warning (with -Dmaven.plugin.validation=VERBOSE)

```
[WARNING] Plugin validation issues were detected in 1 plugin(s)
[WARNING] 
[WARNING]  * io.repaint.maven:tiles-maven-plugin:2.36
[WARNING]   Plugin issue(s):
[WARNING]    * Plugin depends on the deprecated Maven 2.x compatibility layer, which may not be supported in Maven 4.x
```

**Comment by talios** [comment]
Weird - I'd thought we'd resolved this but obviously not - am looking at that currently.  Simply dropping `maven-compat` is causing a few larger changes I need to work out.

The good thing at least, is that tiles is working now under Maven 4 alpha builds.
