### ISSUE TITLE
Release procedure

### ISSUE THREAD

**Issue by lfvjimisola** [repaint-io/maven-tiles#145]
Would it be possible to use GitHub Releases in addition with tags, and not just tags, when creating a new version/release?

It would allow for release notes which are currently lacking. It's quite relevant to know what differences there are between two versions. Using GitHub releases would also give more context information when using bots such as renovate och dependabot.

**Comment by talios** [comment]
I've been meaning to setup https://github.com/jreleaser into the release process for ages, we do maintain the `CHANGELOG.adoc` file, but having that more visible would be good.

Lately most builds have just been dependency updates, and looking into supporting the upcoming Maven 4 (which currently has issues).
