### ISSUE TITLE
mixin fails on spring boot projects 

### ISSUE THREAD

**Issue by jskjons** [repaint-io/maven-tiles#25]
I'm attempting to use this plugin on a spring boot project and I'm getting this exception when it runs:

    org.apache.maven.InternalErrorException: Internal error: java.lang.IllegalArgumentException: no model resolver provided, cannot resolve parent POM org.springframework.data.build:spring-data-build:1.5.2.RELEASE for POM org.springframework.data:spring-data-releasetrain:Evans-SR2

A similar issue seems to have been ran into by another plugin doing some different maven hackery:

https://jira.codehaus.org/browse/MOJO-2032

Some comments on that issue seem to indicate the issue is related to the scope=import dependencies in the dependencyManagement section of spring-boot-dependencies.

**Comment by rvowles** [comment]
Thats entirely possible, Spring's use of Maven remains an abomination however, its an abomination  that should still work. It could be that the Maven Model Merge doesn't support it, but it is easy enough to check.

**Comment by jskjons** [comment]
Here's an example pom that will repro the issue: 

	<?xml version="1.0" encoding="UTF-8"?>
	<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
		<modelVersion>4.0.0</modelVersion>
		<parent>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-parent</artifactId>
			<version>1.2.2.RELEASE</version>
		</parent>
		<artifactId>mixin-testing</artifactId>
		<groupId>mixin.testing</groupId>
		<name>Spring Boot Simple Sample</name>
		<version>1.0-SNAPSHOT</version>
		<dependencies>
			<dependency>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-starter</artifactId>
			</dependency>
			<dependency>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-starter-test</artifactId>
				<scope>test</scope>
			</dependency>
		</dependencies>
		<build>
			<plugins>
				<plugin>
					<groupId>org.springframework.boot</groupId>
					<artifactId>spring-boot-maven-plugin</artifactId>
				</plugin>
				<plugin>
					<groupId>io.repaint.maven</groupId>
					<artifactId>tiles-maven-plugin</artifactId>
					<version>1.8</version>
					<extensions>true</extensions>
					<configuration>
						<filtering>false</filtering>
						<tiles>
						<tile>it.session.maven.tiles:session-license-tile:0.8</tile>
						</tiles>
					</configuration>
				</plugin>
			</plugins>
		</build>
	</project>

**Comment by ratemyduck** [comment]
Is this pom a child of another pom (which is not it's parent)? This was the case for me, and I got the exact same error.

Anyway, I resolved the error by adding child element <relativePath/> to the parent element.

**Comment by talios** [comment]
I believe the 1.8 version of the plugin doesn't like tiles in children, this is fixed in HEAD@master - and that also prevents including the tile plugin in the parent/pom as well ( and also changes how the tiles are published ( it actually attaches them properly ) ).

**Comment by akanter** [comment]
I'm seeing a similar issue with a different `<scope>import</scope>` artifact (homegrown) using maven-tiles 2.2.
```
Caused by: java.lang.IllegalArgumentException: no model resolver provided, cannot resolve parent POM com.internal.hadoop.elephant-plug:elephant-plug:1.1.0 for POM com.internal.hadoop.elephant-plug:hadoop-bom:[unknown-version]
```

I've tried putting it in both the parent pom where that dependency is declared and also in child package and I get the same errors. Any guidance here or even idea of how it might be fixed via PR?

**Comment by talios** [comment]
@akanter are you able to put that in a reproducible public repo anywhere?

**Comment by rvowles** [comment]
thats a pretty spectacular stack trace.

**Comment by rvowles** [comment]
found it. fix coming.
