### ISSUE TITLE
maven-tiles does nothing in large project

### ISSUE THREAD

**Issue by mattthebig** [repaint-io/maven-tiles#26]
I've been trying to get maven-tiles working across several projects. In a project with no parent and no modules it works very nicely. But applying the same plugin config to either the parent or a child of a multi-module component maven-tiles does not have any effect (nor does it print its reassuring 'tiles-maven-plugin: Injecting 3 tiles as intermediary parent artifact's...').

I took from https://github.com/repaint-io/maven-tiles/issues/22 that something should work. Even if I have to copy the maven-tiles plugin config into each sub-module we'd still get heaps out of this plugin.

I've tried with maven-tiles 1.8 on maven 3.0.5, and 3.3.3.

```xml
            <plugin>
                <extensions>true</extensions>
                <groupId>io.repaint.maven</groupId>
                <artifactId>tiles-maven-plugin</artifactId>
                <version>1.8</version>
                <inherited>true</inherited>
                <configuration>
                    <tiles>
                        <tile>nz.co.eroad:checkstyle-level2-tile:1.0.0</tile>
                    </tiles>
                </configuration>
            </plugin>
```

**Comment by talios** [comment]
I've just released 2.2 which fixes various issues with parent/children in the 1.x series.  As part of this, you can no longer specify the plugin in a parent pom, but include it in each child ( there is a known issue with this issuing some warnings, but everything _seems_ to work.

Note also that 2.x also fixes an issue in how tiles were attached/deployed, and existing/legacy tiles need to be referenced different:

    <tile>com.smxemail.tiles:com.smxemail.tiles.enforcements:pom:tile-pom:[1.0.0,2.0.0)</tile>

**Comment by rvowles** [comment]
Can we close this @talios ?

**Comment by talios** [comment]
Closing this as obsolete.  Multi-module builds work for me at $work and no response from OP.
