### ISSUE TITLE
Using tiles in a multi-module project issues warnings over duplicate tile usage

### ISSUE THREAD

**Issue by talios** [repaint-io/maven-tiles#28]
Under tiles-maven-plugin 2.2 using a multi-module project, maven reports a warning for duplicate tiles.

    [WARNING] tiles-maven-plugin in project smx3:smx3.agreement:14.1.74-SNAPSHOT requested for same tile dependency com.smxemail.tiles:com.smxemail.tiles.enforcements:[1.0.0,2.0.0)
    [WARNING] tiles-maven-plugin in project smx3:smx3.agreement:14.1.74-SNAPSHOT requested for same tile dependency com.smxemail.tiles:com.smxemail.tiles.osgiservices:[1.0.0,2.0.0)

The builds all seem to build fine however...

**Comment by Gawen-pjr** [comment]
Hi guys,

Just pushed a little patch resolving this issue.
Note that the problem was much deeper than a simple warning log as tiles could be wrongly mixed-in if projects in reactor don't use the same set of tiles.

**Comment by rvowles** [comment]
Hopefully @talios can do a release before going to work this morning :-)

**Comment by talios** [comment]
And release before I went to work this morning I did :)

**Comment by Gawen-pjr** [comment]
Thank you for your reactivity ;-)

I just pushed 2 suggestions on gerrithub concerning version range resolution.
