### ISSUE TITLE
Cannot deploy tile with composed distributionManagement

### ISSUE THREAD

**Issue by Gawen-pjr** [repaint-io/maven-tiles#29]
When following the README guide for defining a tile using itself a nexus-release-tile, I get an error when trying to deploy the project.

pom.xml :
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

  <modelVersion>4.0.0</modelVersion>
  <groupId>com.example.maven.tiles</groupId>
  <artifactId>test-tile</artifactId>
  <packaging>tile</packaging>
  <version>1.0-SNAPSHOT</version>

  <build>
    <plugins>
      <plugin>
        <groupId>io.repaint.maven</groupId>
        <artifactId>tiles-maven-plugin</artifactId>
        <version>2.2</version>
        <extensions>true</extensions>
        <configuration>
          <filtering>false</filtering>
          <tiles>
            <tile>com.example.maven.tiles:nexus-release-tile:[1.0, 2)</tile>
          </tiles>
        </configuration>
      </plugin>
    </plugins>
  </build>

</project>
```

on `mvn deploy`, I get the following error :
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.7:deploy (default-deploy) on project test-tile: Deployment failed: repository element was not specified in the POM inside distributionManagement element or in -DaltDeploymentRepository=id::layout::url parameter -> [Help 1]
```

But with `mvn help:effective-pom`, I effectively see the distributionManagement section.

PS : on `mvn deploy`, the log clearly says that the `nexus-release-tile` is mixed in the pom.

**Comment by talios** [comment]
I have a suspicion that tiles _can't_ be used for releases.  I remember we wrote that up as an example at the start of the project, but at that stage tiles didn't quite work as expected.  Even now, I have a version of this tile that didn't work ( due to various things the release plugin itself does ).

At the time I was too busy to investigate exactly what the release plugin was doing to see _why_ it was failing.

**Comment by Gawen-** [comment]
Thank you for the reply.

As a workaround, I've set the `altXXXDeploymentRepository` configuration properties of `maven-deploy-plugin` in my `nexus-release-tile`. With that the deploy goal works as expected.

**Comment by talios** [comment]
`tiles-maven-plugin` 2.5 has now been released and should be in central soon with the release fixes.  Note - in order to use oss.sonatype.org you'll also need to use the flatten-maven-plugin.

**Comment by rvowles** [comment]
did we document that?

**Comment by talios** [comment]
I don't think we have actually - have raised that as #44.
