### ISSUE TITLE
MavenSession#getAllProjects method not found

### ISSUE THREAD

**Issue by talios** [repaint-io/maven-tiles#39]
Looks like [`MavenSession#getAllProjects`](https://github.com/apache/maven/blob/master/maven-core/src/main/java/org/apache/maven/execution/MavenSession.java) is a not a blessed method and even carries a comment of:

    /** This is a provisional method and may be removed */

It looks like this was actually removed in the upcoming Maven 3.3.7 release, and also not available in the version of Maven IntelliJ IDEA ships with by default.

**Comment by rvowles** [comment]
If you spot this, we need to know what it has been replaced with. There is possibly "projects".

**Comment by rvowles** [comment]
There is no 3.3.7 or 3.3.8 - only 3.3.3 and 3.3.9

http://archive.apache.org/dist/maven/maven-3/

**Comment by rvowles** [comment]
we are not using getAllProjects, it doesn't exist in 3.2.x and is new and deprecated in 3.3.x it appears.

**Comment by talios** [comment]
This was actually resolved in commit edc5b1135444c1a1706b02488910e5ec1e8a64cb, I forgot to tag the issue tho.

**Comment by talios** [comment]
RE: There is no 3.3.7 or 3.3.8 - only 3.3.3 and 3.3.9  - there _were_, they were versions up for release vote. And that was the version where the change was noticed.

**Comment by nrvmodi** [comment]
I had downgrade my maven version from 3.3.9 to 2.2.1 and my problem was resolved.
