### ISSUE TITLE
Upgraded from 1.5 to 2.7, my tiles cannot be resolved.

### ISSUE THREAD

**Issue by snigel** [repaint-io/maven-tiles#45]
This is my configuration:
```
  <build>
    <plugins>
      <plugin>
        <groupId>io.repaint.maven</groupId>
        <artifactId>tiles-maven-plugin</artifactId>
        <version>2.7</version>
        <extensions>true</extensions>
        <configuration>
          <tiles>
            <tile>com.jeppesen.jcms:aggregate-tile:tile::[1.0.3, 2.0.0)</tile>
          </tiles>
        </configuration>
      </plugin>
    </plugins>
  </build>
```
After upgrading from 1.5 to 2.7 I get the following error message:
```
Failure to find group:artifact:xml:1.2.3 in http://nexusserver/nexus/content/groups/public was cached in the local repository, resolution will not be reattempted until the update interval of central-mirror has elapsed or updates are forced
```
This is indeed correct, because my tiles are not of packaging type "xml" but packaging type "tile".
From what I can see on the front page, the packaging for tiles should still be "tile", so what is happening here?

Looking at other versions this seems to be moving around a bit. The last version I get to resolve correctly is 1.8.

In 2.1 it looks like this:
```
groupid:artifactid:tile:tile-pom:1.2.3
```
That fails, because the version is not "tile" and the packaging is not "tile-pom"

2.2 and upwards has the same behavior as 2.7.

**Comment by talios** [comment]
If you want to use tiles generated with the 1.x series, you will have to specify the tile as:

    <tile>com.jeppesen.jcms:aggregate-tile:tile:pom:tile-pom:[1.0.3, 2.0.0)</tile>

Or re-release the tile using 2.x so the the artifact is attached correctly.  1.x was actually attaching the the tile file as a non-primary artifact.

**Comment by snigel** [comment]
Thank you Talios, that worked, now my old tiles resolve.
