### ISSUE TITLE
Create mechanism to share properties/configuration between pom.xml and its attached tile.xml

### ISSUE THREAD

**Issue by akanter** [repaint-io/maven-tiles#55]
When creating a checkstyle artifact jar with a tile attached, I had to repeat a lot of the configuration between the pom.xml and the tile.xml. It'd be neat if there were some streamlined way to pass configuration from the pom to the tile.

**Comment by stickycode** [comment]
There is now, you can use standard filtering to replace values in the tile.xml, just enable filtering in the tile configuration
```
<confguration>
  <filtering>true</filtering>
</configuration>
```

@talios @rvowles can close this one...
