### ISSUE TITLE
Unable to publish to oss.sonatype.org under 2.8

### ISSUE THREAD

**Issue by talios** [repaint-io/maven-tiles#56]
It seems some change between 2.7 and 2.8 has broken the usage of the `flatten-maven-plugin` when publishing to `oss.sonatype.org`:

Invalid POM: /com/theoryinpractise/halbuilder-styleguide-tile/1.0.4/halbuilder-styleguide-tile-1.0.4.pom: License information missing, SCM URL missing, Developer information missing

**Comment by rvowles** [comment]
2.10 works fine.
