### ISSUE TITLE
mvn:deploy on project with packaging tile (1.0.0 i.e. release) - tile.xml is lost

### ISSUE THREAD

**Issue by cthorburn** [repaint-io/maven-tiles#68]
I can't deploy my tiles. They work fine but I can't share them effectively (local .m2 exhibits the same problem as Nexus)

when I deploy them there is no suggestion of a problem from Maven but the tile.xml is not transferred to the repo.

**Comment by talios** [comment]
Do you have an example project we can look at?

**Comment by mykelalvis** [comment]
Are you certain that your pom has `<extensions>true</extensions>` in the plugin config for maven-tiles?

**Comment by rvowles** [comment]
It looks like @cthorburn has resolved this issue or no longer faces it, perhaps we should close this issue?
