### ISSUE TITLE
Tiles and parent poms are not merging properly

### ISSUE THREAD

**Issue by michaellasmanis** [repaint-io/maven-tiles#80]
After doing some testing with the fix for #79, I noticed that tiles and parent poms are not merging together nicely.  I working on it currently and should have a patch in the next day or so.

@talios please hold the release for the fix for this issue.

**Comment by michaellasmanis** [comment]
Patch and integration tests pushed to Gerrit: https://review.gerrithub.io/c/repaint-io/maven-tiles/+/418545

@talios Sorry this took a bit longer than I expected but I kept finding corner cases.

**Comment by talios** [comment]
On 9 Jul 2018, at 3:03, Michael Lasmanis wrote:

> [@talios](<https://github.com/talios>) Sorry this took a bit longer than I expected but I kept finding corner cases.

No worries - I was pre-occupied with personal issues so didn't really notice.  Merged!

I guess we could cut a release with these changes, unless @timothysparg got anywhere further with the profile issue...


---
"The ease with which a change can be implemented has no relevance at all to whether it is the right change for the (Java) Platform for all time." &mdash; Mark Reinhold.

Mark Derricutt
http://www.theoryinpractice.net
http://www.chaliceofblood.net
http://plus.google.com/+MarkDerricutt
http://twitter.com/talios
http://facebook.com/mderricutt

**Comment by michaellasmanis** [comment]
I'm good to wait a bit.  I've got 2.12-SNAPSHOT in my local maven repo but I wouldn't mind getting off the snapshot version.
