### ISSUE TITLE
os-maven-plugin extension does not run when defined in a tile

### ISSUE THREAD

**Issue by peterjanes** [repaint-io/maven-tiles#94]
Given this tile.xml:

```
<project>
  <build>
    <extensions>
      <extension>
        <groupId>kr.motd.maven</groupId>
        <artifactId>os-maven-plugin</artifactId>
        <version>1.6.1</version>
      </extension>
    </extensions>
  </build>
</project>
```
and a project that imports it

```
...
      <plugin>
        <groupId>io.repaint.maven</groupId>
        <artifactId>tiles-maven-plugin</artifactId>
        <configuration>
          <tiles>
            <tile>com.example:os-tile:[1.0-SNAPSHOT,2)</tile>
          </tiles>
        </configuration>
      </plugin>
...
```
the extension isn't invoked.

I suspect this is common to any extensions, and may not be possible to work around; if so, it's probably worth documenting and/or adding as a build smell.

**Comment by peterjanes** [comment]
In case it's useful, here's [os-maven-plugin](https://github.com/trustin/os-maven-plugin). Also, `mvn help:effective-pom` does show `os-maven-plugin` in `<extensions>`.

**Comment by bvella** [comment]
Maven determines extensions from the models it loads, before the tiles extension has the change to inject the parents. As such, to my knowledge, this is not possible. The extension will show up in the effective pom as this will dump out the flattened model after the tiles plugin injects the parents.

**Comment by peterjanes** [comment]
I thought as much. Would you like a PR for an `extensions` smell?

**Comment by talios** [comment]
@peterjanes if it doesn't work at all ( which has been my experience ) - maybe we should just be failing the build full stop, rather than having a smell that ultimate won't do what you expect/assume.

**Comment by rvowles** [comment]
Failing the build of the tile? I would go with that, a smell is a bad build
practice, something that won't work at all is an error condition.
